In [1]:
# derste aldığım notlar 20

import numpy as np

# numpy array(dizi)

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem) # np.array kullanarak listeyi diziye çevirdik

array([20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
type(matrixListesi)

list

In [8]:
matrixListesi[0]

[10, 20, 30]

In [9]:
np.array(matrixListesi) 

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# *arange

eskiden list(range(0,10)) gibi bir komut yazıp 0 dan 10 a kadar olan sayıları yazdırmayı istiyorduk şimdi de numpy da bu nasıl yapılıyor onu göreceğiz :)

In [10]:
np.arange(0,10)  #bu komut 0 dan 10 a kadar array dizisi oluşturur.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,2) # 0 dan 20 ye kadar 2 şer arttırarak git

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.arange(30) #0 dan 29 a kadar sayıları dizer

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# zeros

In [13]:
np.zeros(5) # içerisinde 5 tane sıfır olan dizi oluşturur.

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,2))  #dizi içerisinde dizi matrix oluşturdu

array([[0., 0.],
       [0., 0.]])

In [15]:
np.ones(5) # dizi içerisinde 5 tane bir olan dii oluşturur

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# *linspace

In [17]:
np.linspace(0,22,5)

array([ 0. ,  5.5, 11. , 16.5, 22. ])

yukarıdaki durum ilk bakışta arange'e benzese de farklı, np.linspace(0,22,5) komutunda demek istediğimiz 0 dan başla 22 ye kadar(22 de dahil) 5 parçaya böl, yani buradaki 5 kaçar kaçar gittiğine değil kaç parçaya bölüneceğini söyler, aralarındaki fark eşittir

In [18]:
np.linspace(1,39,6)

array([ 1. ,  8.6, 16.2, 23.8, 31.4, 39. ])

In [19]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# eye

In [21]:
np.eye(3) # biraz daha matrix le ilgili çokta kullanılmıyo

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random 

In [23]:
np.random.randn(4)

array([-0.21141207, -0.29325573, -0.17513427, -1.22857535])

In [24]:
np.random.randn(4,5)

array([[-0.75605461, -0.77973868, -0.5816354 ,  0.55874945, -0.42805286],
       [-0.61131367,  0.00390247,  0.99135453, -0.69619562,  0.02305239],
       [-0.26977821,  0.01939729, -0.4597408 ,  1.21855069,  1.27700211],
       [-0.7784365 , -0.00842331, -1.19947155,  0.14910388,  0.71219687]])

In [25]:
np.random.randint(1,10)  # int değer döndürür 10 dahil olmaz

2

In [26]:
np.random.randint(1,10,5)

array([8, 9, 7, 2, 4])

In [27]:
np.random.randint(1,300,5)

array([ 89, 171,  79,  62, 198])

In [28]:
benimNumpyDizim = np.arange(30)

In [29]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
benimRandomDizim = np.random.randint(0,100,20)

In [31]:
benimRandomDizim

array([49, 18, 88, 26,  8, 47,  6, 22,  7, 55, 27, 14, 62, 70, 84, 36, 63,
        2,  9, 16])

# numpy dizi methodları

In [32]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

yukarıdaki reshape(5,6) yeniden şekillendir dersek ve ayrıca (5,6) matrix istememizin sebebi yukarıda 30 adet benimNumpyizim tanımladığımız için 

In [33]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
benimNumpyDizim.max() # bir dizinin içerisindeki en yüksek sayıyı gösterir

29

In [35]:
benimRandomDizim.max() # bir dizinin içerisindeki en yüksek sayıyı gösterir

88

In [36]:
benimRandomDizim.argmax() # .argmax() benimRandomDizim dizisindeki en yüksek sayının indeksini gösterir

2

In [37]:
benimRandomDizim.argmin() # .argmin() benimRandomDizim dizisindeki en küçük sayının indeksini gösterir

17

In [38]:
benimNumpyDizim.shape

(30,)

In [39]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [40]:
reshapeDizim.shape

(5, 6)