In [1]:
# derste aldığım notlar 21
import numpy as np

In [2]:
benimDizimmi = np.arange(0,15,2)

In [3]:
benimDizimmi

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [4]:
benimDizimmi[4]

8

yukarıdaki benimDizim[4] kommutunda 4 bizim indeksimizdir e sonuç bize 4 üncü indeksin hangi sayıya denk geldiğini verir

In [5]:
benimDizim = np.arange(15)

In [6]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
benimDizim[3:5]

array([3, 4])

yukarıdaki benimDizim[3:5] komutundaki [3:5] dizideki 3 ile 5 indeksleri arasındaki dizileri getirir, 5. index dahil olmaz

In [8]:
benimDizimmi[3:7]

array([ 6,  8, 10, 12])

In [9]:
benimDizim[3:8] = -5

In [10]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

yukarıdaki benimDizim[3:8] = -5 komutu dizinin 3 ile 8. indeksleri arasındaki değerleri -5 yapar

In [11]:
baskaDizi = np.arange(0,24)

In [12]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [14]:
slicingDizisi = baskaDizi[4:9]

In [15]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [16]:
slicingDizisi[:] = 700

In [17]:
slicingDizisi

array([700, 700, 700, 700, 700])

yukarıdaki slicingDizisi[:] = 700 komutu o dizideki bütün elemanları 700'e eşitler

In [18]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

yukarıdaki baskaDizi komtunu  verince gördük ki bazı diziler 700 olmuş çünkü slicingDizisindeki değerler 700' e eşitlemiştik ,slicingDizisindeki dizi de baskaDizi dizisindeki bazı dizileri referans aldığından , slıicing dizisinin değişmesi bu diziyi de değiştirir. :) 

In [19]:
ornekDizi = np.arange(0,24)

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasi = ornekDizi.copy()

In [22]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [25]:
ornekDiziKopyaSlicing

array([3, 4, 5])

In [26]:
ornekDiziKopyaSlicing[:] = 800

In [27]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [28]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [29]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

şimdi bir önceki notumda ana dizinin soruda değiştirildiğini açıklamıştım, şimdi ise = ana diziyi deeğiştirmeden, bir dizinin içinden nasıl rakamlar alıp değiştireceğimi açıklayacağım

   öncelikle ornekDizi = np.arange(0,24) komutuyla bir dizi oluşturduk ,SONRA
    
   ornekDiziKopyasi = ornekDizi.copy() bu komutu yazarak ilk dizinin aynısından bir tane daha oluşturduk yani 
       .copy() komutu aynı diziden bir tane daha oluşturur  ancak ilk diziye zarar vermez, ARDINDAN
    
   öncelikle biz ilk oluşturduğumuz dizimizden belli rakamları alıp onlarla bişeyler yapmak isteyince ilk dizi bozulacağı için       istediğimiz işlemleri yapabilmek için ilk diziyle değil ilk diziden oluşturduğumuz copy dizisiyle işlem yapacağız böylece         ilk oluşturduğumuz diziyle istediğimiz işlemleri yapabileceğiz ancak ilk dizimiz bozulmuş olmayacak :)

# matrix

In [30]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [31]:
benimListem

[[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [32]:
benimMatrixDizim = np.array(benimListem) #matrix dizisine çevirdik

In [33]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [34]:
benimMatrixDizim[0]

array([10, 20, 30])

In [35]:
benimMatrixDizim[1][2]

40

In [36]:
benimMatrixDizim[1,2]   #bu komut yukarıdaki benimMatrixDizim[1][2] komutunun aynısıdır

40

In [37]:
benimMatrixDizim[1:]

array([[20, 30, 40],
       [40, 50, 60]])

yukarıdaki benimMatrixDizim[1:] komutu 1.indeksten itibaren bütün indeksleri getirir

In [38]:
benimMatrixDizim[1:,2]

array([40, 60])

yukarıdaki benimMatrixDizim[1:,2] komutu 1. satırdan itibaren sadece 2. index sütunlarının getirilmesi gerektiğini gösterir

In [39]:
benimMatrixDizim[0:,2] # 0. satırdan itibaren 2..sütün indeklerini getirir

array([30, 40, 60])

In [40]:
benimMatrixDizim[2:,2]

array([60])

In [41]:
benimMatrixDizim[2:,1]

array([50])

In [42]:
benimMatrixDizim[1:,2:]

array([[40],
       [60]])

In [43]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [44]:
yeniMatrix = np.array(yeniListe)

In [45]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [47]:
yeniMatrix[[0,2,4]]    # bu komut 0,2 ve 4. indeksleri verir. fancy indexing

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# operasyonlar

In [48]:
yeniBirDizi= np.random.randint(1,100,20) # 1 den 100 e kadar 20 sayı ver

In [49]:
yeniBirDizi

array([87, 60,  4, 71, 41, 23, 70, 76, 62, 81, 54,  1, 31, 99, 75, 29, 19,
       17, 14, 57])

In [50]:
yeniBirDizi > 24

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False, False,
       False,  True])

In [51]:
sonucDizisi = yeniBirDizi > 24

In [52]:
sonucDizisi

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False, False,
       False,  True])

In [53]:
yeniBirDizi[sonucDizisi] # değeri 24 ten büyük olan rakamları verir

array([87, 60, 71, 41, 70, 76, 62, 81, 54, 31, 99, 75, 29, 57])

In [54]:
yeniBirDizi

array([87, 60,  4, 71, 41, 23, 70, 76, 62, 81, 54,  1, 31, 99, 75, 29, 19,
       17, 14, 57])

In [55]:
yeniBirDizi[yeniBirDizi>24] # direk böyle yapsınca da aynı sonucu alırız

array([87, 60, 71, 41, 70, 76, 62, 81, 54, 31, 99, 75, 29, 57])

In [56]:
sonDizi = np.arange(0,24)

In [57]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [59]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [60]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [61]:
sonDizi / sonDizi # 0/0 da sorun yaşadığı için hata versede işlemi yapmaya devam eder

C:\Users\yalci\AppData\Local\Temp\ipykernel_34724\2200616282.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi # 0/0 da sorun yaşadığı için hata versede işlemi yapmaya devam eder


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
np.sqrt(sonDizi)  # sonDizi dizisinin karekökü alındı

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [63]:
np.max(sonDizi)

23

In [64]:
np.min(sonDizi)

0